<a href="https://colab.research.google.com/github/youjuny/Data-test/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_%ED%85%8C%EC%8A%A4%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
stu = pd.read_excel('/content/students.xlsx')

In [ ]:
#1. 국어가 80점 이상인 학생의 이름과 생년월일
stu[stu['국어'] >= 80][['이름','생년월일']]

In [ ]:
#2. 수학이 80점 미만인 학생의 영어와 국어 점수
stu[stu['수학'] < 80][['영어','국어']]

In [ ]:
# 3. 국어와 수학이 90점 이상인 학생의 이름, 수학, 국어 점수
idx = (stu['국어'] >= 90) & (stu['수학'] >= 90)
stu.loc[idx][['이름','수학','국어']]

In [ ]:
# 4. 모든 과목이 60점 미만인 학생의 번호, 이름, 생년월일
idx = (stu['국어'] < 60) & (stu['수학'] < 60) & (stu['영어'] < 60)
stu.loc[idx][['번호','이름','생년월일']]

In [ ]:
# 5. 대전 지역 학생들의 이름, 국어, 영어, 수학 점수
stu.loc[stu['지역명'] == '대전'][['이름','국어','영어','수학']]

In [ ]:
# 1. 학생들의 평균 구하기
stu.mean(axis=1)

In [25]:
# 학생들의 총점 구하기
stu.sum(axis=1)

In [27]:
# 2. 학생들의 평균이 높은 순으로 정렬. 만약 평균이 같다면 학번으로 오름차순
stu['평균'] = stu.mean(axis=1)
stu.sort_values(['평균','번호'], ascending=[False,True])

<ipython-input-27-4f01275c7b58>:2: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  stu['평균'] = stu.mean(axis=1)
<ipython-input-27-4f01275c7b58>:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  stu['평균'] = stu.mean(axis=1)

    번호   이름  국어  영어  수학 지역명       생년월일     평균
94  95  정현연  98  89  85  광주 2050-05-19  91.75
88  89  박명희  83  94  94  대구 2050-07-02  90.00
93  94  이현진  97  96  72  대구 2050-08-04  89.75
81  82  정준동  82  95  99  울산 2050-04-07  89.50
83  84  장혜은  94  76  99  서울 2050-07-12  88.25
..  ..  ...  ..  ..  ..  ..        ...    ...
20  21  이명수  62  88  62  서울 2050-04-01  58.25
4    5  김혜수  83  76  67  대전 2050-01-25  57.75
0    1  이현진  68  77  81  대전 2050-08-17  56.75
2    3  강준은  63  85  64  울산 2050-10-22  53.75
24  25  장철운  61  62  64  부산 2050-02-05  53.00

[100 rows x 8 columns]